### ISSUE TITLE
BibTeX Keys with asterix * are not parsed

### ISSUE THREAD

**Issue by istvank** [jbibtex/jbibtex#15]
We are using an asterix symbol * in our BibTeX file to indicate five or more authors, for example "ABC*15". Unfortunately it seems that these keys do not get parsed by JBibTeX, there is no entry generated at all.

**Comment by vruusmann** [comment]
Do you want to use the asterisk symbol `*` inside an entry key like this?
```
@article { ABC*15,
  author = "author1 and author2 and author3 and author4 and author5"
}
```

Most likely, the entry is not generated, because you are using JBibTex parser in error recovery mode?

**Comment by istvank** [comment]
Exactly like this. When I use the parser without error recovery mode (simply `parse()` I guess), I get the following exception:
```
org.jbibtex.TokenMgrException: Lexical error at line 1, column 19.  Encountered: "*" (42), after : ""
        at org.jbibtex.BibTeXParserTokenManager.getNextToken(BibTeXParserTokenManager.java:713)
        at org.jbibtex.BibTeXParser.jj_scan_token(BibTeXParser.java:987)
        at org.jbibtex.BibTeXParser.jj_3_6(BibTeXParser.java:816)
        at org.jbibtex.BibTeXParser.jj_2_6(BibTeXParser.java:787)
        at org.jbibtex.BibTeXParser.Entry(BibTeXParser.java:439)
        at org.jbibtex.BibTeXParser.Object(BibTeXParser.java:293)
        at org.jbibtex.BibTeXParser.Database(BibTeXParser.java:246)
        at org.jbibtex.BibTeXParser.parse(BibTeXParser.java:57)
```
which is the asterix. Anything else I should try?

**Comment by istvank** [comment]
Fantastic, it works now..Thanks so much! :+1:
